name: Build and Upload

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Automatyczne uruchomienie raz w tygodniu
  workflow_dispatch:  # Ręczne uruchomienie przez użytkownika

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        ./installResources.ps1

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole converter.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: converter-exe
        path: dist/converter.exe
